module.exports = {
  'ie': '9',
  'edge': '12',
  'firefox': '43',
  'chrome': '41',
  'safari': '8',
  'opera': '38',
  'ios_saf': '7.0',
  'op_mini': 'all',
  'android': '4.1',
  'bb': '7',
  'op_mob': '12',
  'and_chr': '53',
  'and_ff': '49',
  'ie_mob': '10',
  'and_uc': '11',
  'samsung': '4',
};
