// When the property value is true (eg for 'background'), it is supported
// in effectively all browsers (since IE6+, Firefox 2+, Chrome 1+ etc)

module.exports = {
  'all': [{
    values: ['initial', 'inherit', 'unset'],
    support: {
      ie: false,
      edge: false,
      firefox: '27',
      chrome: '37',
      safari: '9.1',
      opera: '24',
      ios_saf: '9.3',
      op_mini: false,
      android: '4.4.3-4.4.4',
      bb: false,
      op_mob: '37',
      and_chr: '53',
      and_ff: '49',
      ie_mob: false,
      and_uc: false,
      samsung: '4',
    }
  }],
  'background',
  'background-attachment': [{
    values: ['fixed'],
    support: {
      ie: '5.5',
      safari: '3.1',
      opera: '9',
      ios_saf: false,
      op_mini: false,
      android: false,
      bb: false,
      and_chr: false,
      and_uc: '11',
      samsung: false,
    }
  }, {
    values: ['local'],
    support: {
      ie: '9',
      firefox: '25',
      safari: '5',
      opera: '10.5',
      ios_saf: false,
      op_mini: false,
      android: false,
      and_chr: false,
      and_uc: false,
      samsung: false,
    }
  }, {
    values: ['scroll', 'initial', 'inherit'],
    support: {
      ios_saf: '5.0-5.1',
      op_mini: false,
      android: false,
      samsung: false,
    }
  }],
  'background-clip': false, // TODO
  'background-color': true,
  'background-image': true,
  'background-origin': false, // TODO
  'background-position': true, // (2 params)
  'background-repeat': [{
    values: ['repeat', 'repeat-x', 'repeat-y', 'no-repeat'],
    support: true,
  }],
  'background-size': false, // TODO
  'border': false, // TODO
  'border-bottom',
  'border-bottom-color',
  'border-bottom-left-radius',
  'border-bottom-right-radius',
  'border-bottom-style',
  'border-bottom-width',
  'border-collapse': [{
    values: ['collapse', 'separate'],
    support: true
  }],
  'border-color': true,
  'border-image',
  'border-image-outset',
  'border-image-repeat',
  'border-image-slice',
  'border-image-source',
  'border-image-width',
  'border-left',
  'border-left-color',
  'border-left-style',
  'border-left-width',
  'border-radius',
  'border-right',
  'border-right-color',
  'border-right-style',
  'border-right-width',
  'border-spacing': true,
  'border-style': true,
  'border-top',
  'border-top-color',
  'border-top-left-radius',
  'border-top-right-radius',
  'border-top-style',
  'border-top-width',
  'border-width',
  'bottom': true,
  'box-shadow',
  'caption-side',
  'clear': [{
    values: ['none', 'left', 'right', 'both'],
    support: true,
  }],
  'clip',
  'color': true,
  'content',
  'counter-increment',
  'counter-reset',
  'cursor',
  'direction',
  'display': [{
    values: ['none', 'inline', 'block', 'list-item'],
    support: true,
  }],
  'empty-cells',
  'float': [{
    values: ['none', 'left', 'right'],
    support: true,
  }],
  'font',
  'font-family': true,
  'font-size': true,
  'font-size-adjust',
  'font-stretch',
  'font-style': [{
    values: ['normal', 'italic', 'oblique'],
    support: true,
  }],
  'font-synthesis',
  'font-variant': [{
    values: ['normal', 'small-caps'],
    support: true,
  }],
  'font-weight': true,
  'height': true,
  'left': true,
  'letter-spacing',
  'line-height': true,
  'list-style': true,
  'list-style-image': true,
  'list-style-position': true,
  'list-style-type',
  'margin': true,
  'margin-bottom',
  'margin-left',
  'margin-right',
  'margin-top',
  'max-height',
  'max-width',
  'min-height',
  'min-width',
  'opacity',
  'orphans',
  'outline',
  'outline-color',
  'outline-style',
  'outline-width',
  'overflow': [{
    values: ['visible', 'hidden', 'scroll', 'auto'],
    support: true,
  }],
  'padding': true,
  'padding-bottom',
  'padding-left',
  'padding-right',
  'padding-top',
  'page-break-after',
  'page-break-before',
  'page-break-inside',
  'position': [{
    values: ['static', 'relative', 'absolute'],
    support: true,
  }, {
    values: ['fixed'],
    support: {
      ie: '7',
      ios_saf: '8',
      android: '3',
      op_mini: false,
    },
  }],
  'quotes',
  'right': true,
  'table-layout',
  'text-align': [{
    values: ['left', 'right', 'center', 'justify'],
    support: true,
  }],
  'text-decoration': [{
    values: ['none', 'underline', 'overline', 'line-through'],
    support: true,
  }],
  'text-indent': true,
  'text-transform': [{
    values: ['capitalize', 'uppercase', 'lowercase', 'none'],
    support: true,
  }],
  'top': true,
  'transform',
  'transform-origin',
  'transition',
  'transition-delay',
  'transition-duration',
  'transition-property',
  'transition-timing-function',
  'unicode-bidi',
  'vertical-align',
  'visibility': [{
    values: ['visible', 'hidden'],
    support: true,
  }],
  'white-space',
  'widows',
  'width': true,
  'word-spacing': true,
  'z-index': true,
};
